### ISSUE TITLE
[QUESTION] Can we use other open+closed source models with this project too ?

### ISSUE THREAD

**Issue by Greatz08** [Nutlope/llamacoder#51]
If yes then how and if not then why not ?
Btw there is one open source project called Litellm which can easily help you integrate 100+ LLM's easily so if this project can be used with other LLM's then it will be awesome in my opinion as people will have many more options to choose from :-))

**Comment by SteppeScript** [comment]
Together AI only supports open source LLM models. However, you can fork the repo and replace together AI integration with closed LLM model (Claude, ChatGPT etc...) of your choice.

Since Nutlope is part of Together AI, I don't think he'll be investing his time to add for something Together AI doesn't support.
